config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#top'
  root to: 'books#top'
  devise_for :users

  resources :users, only: [:show, :edit, :update, :index]
  resources :books, only: [:create, :index, :show, :destroy, :update, :edit] do
   resource :favorites, only: [:create, :destroy]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }



    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters,if: :devise_controller?

def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user.id)
end
def after_sign_out
    flash[:notice] = "Signed out successfully."
end

protected

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email, :name])
    devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index, :edit]
  def top
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book.id)
    else
       @books = Book.all
       render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to  books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.user != current_user
       redirect_to new_user_session_path
    else
      if @book.update(book_params)
        flash[:notice] = "You have updated book successfully."
        redirect_to book_path(@book.id)
      else
        render :edit
      end
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def show
   @book_new = Book.new
   @book = Book.find(params[:id])
   @user = User.find_by(id: @book.user_id)
  end

  def destroy
    @books = Book.all
    @book = Book.find(params[:id])
    if @book.user != current_user
       redirect_to new_user_session_path
    else
       @book.destroy
       flash[:notice] = "Book was successfully destroyed."
       redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index, :edit]
  def index
    @users = User.all
    @book = Book.new
    @user = User.find(current_user.id)

  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to  user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="text-center">
  <h1>Editing Book</h1>
  <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this obj from being saved:
      <ul><% @book.errors.full_messages.each do |message| %></ul>
      <li><%= message %></li>
      <% end %>
    <% end %>
  <%= form_with model:@book, local: true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <br><%= f.submit'Update Book' %></br>
  <p><%= link_to"Show",book_path(@book.id) %> | <%= link_to"Back","/books" %></p>
  <% end %>
</div>

app/views/books/index.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>
<div class="container">
  <div class="row">

    <div class='col-md-3'>
      <h1>User info</h1>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
      <% if @user.id == current_user.id %>
        <p><%= link_to edit_user_path(@user) do%>
          <button type="button" class="btn btn-outline-secondary"><i class="fas fa-user-cog"></i></button>
        <% end %></p>
      <% end %>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this obj from being saved:
      <ul><% @book.errors.full_messages.each do |message| %></ul>
      <li><%= message %></li>
      <% end %>
    <% end %>

      <h1>New book</h1>
      <%= form_with model: @book, url:'/books', local:true do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
        <%= f.text_area :body %><br />
        <%= f.submit'Create Book', class: "btn btn-success" %>
      <% end %>
    </table>

    </div>
    <div class='col-md-8 offset-md-1'>
      <h1>Books</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user.id) do %><%= attachment_image_tag book.user, :profile_image, :fill, 10, 10, format: 'jpeg', fallback: "no_image.jpg", size:'50x50' %><% end %></td>
              <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  ♥<%= book.favorites.count %>
                <% end %>
              </p>
                <% else %>
              <p>
                <%= link_to book_favorites_path(book), method: :post do %>
                  ♡<%= book.favorites.count %>
                <% end %>
              </p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>
<div class="container">
  <div class="row">

  <div class="col-md-3">

    <h1>User info</h1>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>

        <p><%= link_to edit_user_path(@user) do%>
          <button type="button" class="btn btn-outline-secondary"><i class="fas fa-user-cog"></i></button>
        <% end %></p>

    <h1>New book</h1>
      <%= form_with model: @book_new, url:'/books', local:true do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
        <%= f.text_area :body %><br />
        <%= f.submit'Create Book', class: "btn btn-success" %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table table-hover">
        <% if current_user.id %>
        <tbody>
            <tr>
              <td><%= link_to user_path(@user.id) do %><%= attachment_image_tag @user, :profile_image, :fill, 10, 10, format: 'jpeg', fallback: "no_image.jpg" %><br />
              <%= @user.name %><% end %></td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <td>
                <% if @book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  ♥<%= @book.favorites.count %>
                <% end %>
              </p>
                <% else %>
              <p>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  ♡<%= @book.favorites.count %>
                <% end %>
              </p>
                <% end %>
              </td>
              <% if @book.user == current_user %>
              <td><%= link_to"Edit", edit_book_path(@book), class: "btn btn-success" %></td>
              <td><%= link_to"Destroy", book_path(@book.id),class: "btn btn-danger", method: :delete, "data-confirm" => "Are you sure?" %></td>
              <% else %>
              <td></td>
              <td></td>
              <% end %>
            </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/top.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>
<div class="text-center">
  <h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
    <p>In <i class="fas fa-book"></i>Bookers,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>
    <p><%= link_to "Log in", new_user_session_path, class:"btn btn-primary" %></p>
    <p><%= link_to "Sign up", new_user_registration_path, class:"btn btn-success" %></p>
    </div>

app/views/homes/top.html.erb
<h1 class="text-center">Welcome to <i class="fas fa-book"></i>Bookers!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-secondary">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-1 text-white" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
              <span><i class="fas fa-home"></i>Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: 'nav-link text-white' do %>
             <span><i class="fas fa-users"></i>Users</span>
              <% end %>
            </li>
            <li>
              <%= link_to  books_path, class: 'nav-link text-white' do %>
              <span><i class="fas fa-book-open"></i>Books</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
              <span><i class="fas fa-sign-out-alt"></i>logout</span>
              <% end %>
            </li>

            <% else %>
            <li>
              <%= link_to '/', class: 'nav-link text-white' do %>
              <span><i class="fas fa-home"></i>Home</span>
              <% end %>
            </li>
            <li>
              <%= link_to '/home/about',class: 'nav-link text-white' do %>
              <span><i class="fas fa-link"></i>About</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
              <span><i class="fas fa-user-plus"></i>sign up</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
              <span><i class="fas fa-sign-in-alt"></i>login
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <p class="text-center">CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="text-center">
<h1>User info</h1>
<% if @user.errors.any? %>
    <%= @user.errors.count %>
    <ul><% @user.errors.full_messages.each do |message| %></ul>
      <li><%= message %></li>
    <% end %>
  <% end %>
<%= form_with model:@user, local:true do |f| %>
  <body>

      <label for="inputName">Name</label><br/>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%><br />
      <label for="inputImage">Image</label><br/>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %><br/>
      <label for="inputIntroduction">Introduction</label><br/>
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介文"%><br/>
      <%= f.submit "Update User" %>

  </body>
<% end %>
</div>

app/views/users/index.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <h1>User info</h1>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
      <% if @user.id == current_user.id %>
        <p><%= link_to edit_user_path(@user) do%>
          <button type="button" class="btn btn-outline-secondary"><i class="fas fa-user-cog"></i></button>
        <% end %></p>
      <% end %>
      <h1>New book</h1>
      <%= form_with model: @book, url:'/books', local:true do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
        <%= f.text_area :body %><br />
        <%= f.submit'Create Book', class: "btn btn-success" %>
      <% end %>
    </table>

    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 10, 10, format: 'jpeg', fallback: "no_image.jpg", size:'50x50' %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user.id)%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>
<div class="container">
  <div class="row">

  <div class="col-md-3">

    <h1>User info</h1>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'50x50' %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
        <p><%= link_to edit_user_path(@user) do%>
          <button type="button" class="btn btn-outline-secondary"><i class="fas fa-user-cog"></i></button>
        <% end %></p>
    <h1>New book</h1>
      <%= form_with model: @book, local:true do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
        <%= f.text_area :body %><br />
        <%= f.submit'Create Book', class: "btn btn-success" %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(@user) do %><%= attachment_image_tag @user, :profile_image, :fill, 10, 10, format: 'jpeg', fallback: "no_image.jpg" %><% end %></td>
              <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>